using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace UIFramework.Editor.CodeGen
{
    /// <summary>
    /// Generates ViewModelRegistry.cs with all ViewModel registrations.
    /// Runs automatically when scripts compile or manually via menu.
    /// </summary>
    public static class ViewModelRegistryGenerator
    {
        private const string OUTPUT_PATH = "Assets/UIFramework/Scripts/DI/Generated/ViewModelRegistry.cs";
        private const string NAMESPACE = "UIFramework.DI.Generated";

        [MenuItem("UIFramework/Code Generation/Generate ViewModel Registry", priority = 200)]
        public static void GenerateRegistry()
        {
            Debug.Log("[ViewModelRegistryGenerator] Scanning for ViewModels...");

            var viewModels = FindAllViewModels();

            if (viewModels.Count == 0)
            {
                Debug.LogWarning("[ViewModelRegistryGenerator] No ViewModels found.");
                return;
            }

            var code = GenerateCode(viewModels);
            WriteCodeToFile(code);

            Debug.Log($"[ViewModelRegistryGenerator] Generated registry with {viewModels.Count} ViewModel(s)");
            EditorUtility.DisplayDialog("Success",
                $"Generated ViewModelRegistry.cs with {viewModels.Count} ViewModel(s)!",
                "OK");
        }

        /// <summary>
        /// Auto-generate on script compilation (optional - can be disabled if too slow)
        /// </summary>
        [UnityEditor.Callbacks.DidReloadScripts]
        private static void OnScriptsReloaded()
        {
            // Auto-generate registry when scripts compile
            // Comment this out if you prefer manual generation only
            GenerateRegistryIfNeeded();
        }

        private static void GenerateRegistryIfNeeded()
        {
            // Only auto-generate if registry doesn't exist or ViewModels changed
            if (!File.Exists(OUTPUT_PATH))
            {
                Debug.Log("[ViewModelRegistryGenerator] Auto-generating registry...");
                GenerateRegistry();
            }
        }

        private static List<Type> FindAllViewModels()
        {
            var viewModelBaseType = typeof(UIFramework.Core.ViewModelBase);
            var viewModels = new List<Type>();

            // Get all assemblies
            var assemblies = AppDomain.CurrentDomain.GetAssemblies();

            foreach (var assembly in assemblies)
            {
                var assemblyName = assembly.GetName().Name;

                // Skip Unity and system assemblies
                if (ShouldSkipAssembly(assemblyName))
                {
                    continue;
                }

                try
                {
                    var types = assembly.GetTypes()
                        .Where(t => t.IsClass &&
                               !t.IsAbstract &&
                               viewModelBaseType.IsAssignableFrom(t) &&
                               t != viewModelBaseType &&
                               // Exclude examples
                               !t.Namespace?.StartsWith("UIFramework.Examples") == true);

                    viewModels.AddRange(types);
                }
                catch (Exception ex)
                {
                    Debug.LogWarning($"[ViewModelRegistryGenerator] Error scanning {assemblyName}: {ex.Message}");
                }
            }

            return viewModels.OrderBy(t => t.FullName).ToList();
        }

        private static bool ShouldSkipAssembly(string assemblyName)
        {
            return assemblyName.StartsWith("Unity") ||
                   assemblyName.StartsWith("System") ||
                   assemblyName.StartsWith("mscorlib") ||
                   assemblyName.StartsWith("netstandard") ||
                   assemblyName.StartsWith("Microsoft") ||
                   assemblyName.StartsWith("Mono.") ||
                   assemblyName.StartsWith("nunit") ||
                   assemblyName.StartsWith("VContainer") ||
                   assemblyName.Contains("Editor");
        }

        private static string GenerateCode(List<Type> viewModels)
        {
            var code = new StringBuilder();

            // Header
            code.AppendLine("// <auto-generated>");
            code.AppendLine("// This file is automatically generated by ViewModelRegistryGenerator.");
            code.AppendLine("// Do not modify manually - changes will be overwritten!");
            code.AppendLine($"// Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            code.AppendLine("// </auto-generated>");
            code.AppendLine();

            // Usings
            code.AppendLine("using VContainer;");
            code.AppendLine();

            // Namespace
            code.AppendLine($"namespace {NAMESPACE}");
            code.AppendLine("{");

            // Class
            code.AppendLine("    /// <summary>");
            code.AppendLine($"    /// Auto-generated ViewModel registry with {viewModels.Count} ViewModel(s).");
            code.AppendLine("    /// </summary>");
            code.AppendLine("    public static class ViewModelRegistry");
            code.AppendLine("    {");

            // Register method
            code.AppendLine("        /// <summary>");
            code.AppendLine("        /// Registers all ViewModels in the project.");
            code.AppendLine("        /// Call this from UIFrameworkInstaller.Configure()");
            code.AppendLine("        /// </summary>");
            code.AppendLine("        public static void RegisterAll(IContainerBuilder builder)");
            code.AppendLine("        {");

            // Register each ViewModel
            foreach (var viewModel in viewModels)
            {
                code.AppendLine($"            builder.Register<{viewModel.FullName}>(Lifetime.Transient);");
            }

            code.AppendLine("        }");
            code.AppendLine("    }");
            code.AppendLine("}");

            return code.ToString();
        }

        private static void WriteCodeToFile(string code)
        {
            var directory = Path.GetDirectoryName(OUTPUT_PATH);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(OUTPUT_PATH, code);
            AssetDatabase.Refresh();
        }
    }
}
