using System;
using UnityEngine;
using VContainer;
using VContainer.Unity;
using UIFramework.Animation;
using UIFramework.Core;
using UIFramework.Events;
using UIFramework.Navigation;
using UIFramework.Configuration;

namespace UIFramework.DI
{
    /// <summary>
    /// VContainer installer for the UIFramework.
    /// Registers all framework services with proper lifetimes.
    /// </summary>
    public class UIFrameworkInstaller : LifetimeScope
    {
        [SerializeField] private UIFrameworkConfig config;
        [SerializeField] private Canvas uiCanvas;

        protected override void Configure(IContainerBuilder builder)
        {
            if (config == null)
            {
                Debug.LogError("[UIFrameworkInstaller] UIFrameworkConfig is not assigned!");
                return;
            }

            if (uiCanvas == null)
            {
                Debug.LogError("[UIFrameworkInstaller] UI Canvas is not assigned! Assign a Canvas in the inspector.");
                return;
            }

            Debug.Log("[UIFrameworkInstaller] Configuring UIFramework services...");

            // Register configuration
            builder.RegisterInstance(config);

            // Register loading (must be before pooling)
            RegisterLoadingServices(builder);

            RegisterPoolingServices(builder);

            // Register core services (UIViewFactory depends on IUIObjectPool)
            RegisterCoreServices(builder);

            // Register navigation
            RegisterNavigationServices(builder);

            // Register animation
            RegisterAnimationServices(builder);

            // Register ViewModels using generated code (zero runtime overhead!)
            RegisterViewModels(builder);

            Debug.Log("[UIFrameworkInstaller] UIFramework services configured.");
        }

        /// <summary>
        /// Registers all ViewModels using auto-generated code.
        /// The ViewModelRegistry is generated by ViewModelRegistryGenerator editor script.
        /// Run "UIFramework > Code Generation > Generate ViewModel Registry" to update.
        /// </summary>
        private void RegisterViewModels(IContainerBuilder builder)
        {
            #if UNITY_EDITOR
            // In editor, check if registry exists and warn if not
            if (!System.IO.File.Exists("Assets/UIFramework/DI/Generated/ViewModelRegistry.cs"))
            {
                Debug.LogWarning("[UIFrameworkInstaller] ViewModelRegistry.cs not found. Run 'UIFramework > Code Generation > Generate ViewModel Registry' to create it.");
                return;
            }
            #endif

            // Use generated registry (compile-time, zero runtime overhead)
            try
            {
                DI.Generated.ViewModelRegistry.RegisterAll(builder);
                Debug.Log("[UIFrameworkInstaller] Registered ViewModels using generated code");
            }
            catch (Exception ex)
            {
                Debug.LogError($"[UIFrameworkInstaller] Failed to register ViewModels: {ex.Message}");
                Debug.LogError("Run 'UIFramework > Code Generation > Generate ViewModel Registry' to regenerate the registry.");
            }
        }

        private void RegisterCoreServices(IContainerBuilder builder)
        {
            // Event bus - singleton
            builder.Register<UIEventBus>(Lifetime.Singleton);

            // View factory - singleton (pass Canvas reference from installer)
            builder.Register<IUIViewFactory, UIViewFactory>(Lifetime.Singleton)
                .WithParameter(uiCanvas);
        }

        private void RegisterNavigationServices(IContainerBuilder builder)
        {
            // State machine - singleton
            builder.Register<UIStateMachine>(Lifetime.Singleton);

            // Navigation stack - singleton
            builder.Register<INavigationStack, NavigationStack>(Lifetime.Singleton)
                .WithParameter(config.MaxNavigationStackDepth);

            // Navigator facade - singleton
            builder.Register<UINavigator>(Lifetime.Singleton);
        }

        private void RegisterAnimationServices(IContainerBuilder builder)
        {
            // Animator - singleton
            builder.Register<IUIAnimator, DOTweenUIAnimator>(Lifetime.Singleton);
        }

        private void RegisterLoadingServices(IContainerBuilder builder)
        {
            if (config.UseAddressables)
            {
                #if UIFRAMEWORK_ADDRESSABLES
                builder.Register<IUILoader, UIFramework.Loading.AddressablesUILoader>(Lifetime.Singleton);
                Debug.Log("[UIFrameworkInstaller] Registered AddressablesUILoader");
                #else
                Debug.LogWarning("[UIFrameworkInstaller] Addressables is enabled in config but not installed. Falling back to Resources.");
                builder.Register<IUILoader, UIFramework.Loading.ResourcesUILoader>(Lifetime.Singleton);
                #endif
            }
            else
            {
                builder.Register<IUILoader, UIFramework.Loading.ResourcesUILoader>(Lifetime.Singleton);
                Debug.Log("[UIFrameworkInstaller] Registered ResourcesUILoader");
            }
        }

        private void RegisterPoolingServices(IContainerBuilder builder)
        {
            builder.Register<IUIObjectPool, UIFramework.Pooling.UIObjectPool>(Lifetime.Singleton);
            Debug.Log("[UIFrameworkInstaller] Registered UIObjectPool (using Unity's ObjectPool internally)");
        }

        /// <summary>
        /// Called after the container is built.
        /// Use this to perform initialization that requires resolved services.
        /// </summary>
        protected override void Awake()
        {
            base.Awake();

            DontDestroyOnLoad(gameObject);

            // Initialize static UIFramework facade
            Core.UIFramework.Initialize(Container);

            uiCanvas.transform.SetParent(transform);
        }

        protected override void OnDestroy()
        {
            Core.UIFramework.Reset();
            base.OnDestroy();
        }
    }
}
